### ISSUE TITLE
dse-server container : permission issue on mounted volumes, not owned by user 999

### ISSUE THREAD

**Issue by bobbybobby** [datastax/docker-images#57]
The dse-server container creates a user `dse` with a hard coded UID of 999. When mounting a volume from the host on `/var/lib/cassandra`, the permissions on the folder are not changed and user `dse` on the container isn't allowed to write to the directory. Resulting in an error (among other write errors)

```
1) An exception was caught and reported. Message: commitlog directory '/var/lib/cassandra/commitlog' or, if it does not already exist, an existing parent directory of it, is not readable and writable for the DSE. Check file system and configuration.
  at com.datastax.bdp.DseModule.configure(Unknown Source)
```

Example of docker-compose to reproduce the problem

```
version: '2'
services:
  dse:
    image: datastax/dse-server:5.1.8
    container_name: my-dse
    environment:
      - DS_LICENSE=accept
    ports:
      - "9042:9042"
    volumes:
      - ${DATA_PATH}/dse/data:/var/lib/cassandra
    networks:
      - mynetwork
``` 

If `${DATA_PATH}/dse/data` exists beforehand, but has an owner UID different than 999 (most likely 1000, default user id on linux machines), the `dse` user on the container can't write in the volume. If the directory doesn't exist on the host beforehand, docker will create it with `root` as owner. Same problem, `dse` user doesn't have the rights to the volume. If we use docker-compose's named volume instead of an absolute path, the problem is the same because the named volume is a directory owned by `root`.

This happen on a linux host, because the container share the kernel with the host and use the same UID and GID permission tables. I believe mac users don't have this problem.

Several workarounds I came up with, none of which I find satisfying : 

- manually setting the ownership of the directory on the host to uid 999, although no such user exist on my host
- using docker-compose `group_add` (equivalent to docker `--group-add` option), to add the GID of the host directory to the groups of `dse` user
- Wrapping the `dse-server` container in a custom container with the following Dockerfile : 

```
FROM datastax/dse-server:5.1.8

USER root
RUN chown dse:dse /var/lib/cassandra
USER dse
```

I wonder why the ownership the directory mounted on `/var/lib/cassandra` isn't set to `dse`, although I see their is a `chown` command in the Dockerfile : https://github.com/datastax/docker-images/blob/826ed297c69240ea45f703be14131b2f5db2be99/server/5.1/Dockerfile#L53
